name: Package with Pyinstaller

on: [push, pull_request]

jobs:

  windows:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: ./dist/windows

  linux:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: ./dist/linux
